config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  'home#new'
  resources :users, only: [:show, :update, :edit, :index,]
  resources :books, only: [:create,:show, :update, :edit, :index,]
  resources :home, only: [:new] do
    get :about, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ユーザー名のバリデーション
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction,length: {maximum: 50}

  # レコード削除時に関連するbooksも削除する(dependent: :destroy)
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @book = Book.new
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params) && (@user == current_user)
    flash[:notice] = "You have updated book successfully.."
    redirect_to user_path(@user.id)
    else
    render action: :edit
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    render action: :edit
    else
    redirect_to user_path(current_user)
    end
  end

  def index
   @book = Book.new
   @users = User.all
  end



  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <h2>User info</h2>

    <!--バリデーションのエラ〜メッセージ-->
    <div id="error_explanation">
     <% if @user.errors.any? %>
      <h3>2 error prohibited this obj from being saved:</h3>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
      <% end %>


<%= form_with model:@user, local:true do |f| %>


<label>Name</label>
<%= f.text_field :name %><br>

<label>Image</label><br>
<%= f.attachment_field :profile_image %><br>

<label>introduction</label>
<%= f.text_area :introduction %><br>
<%= f.submit 'Update User'%><br>
</div>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<!--User infoの部分-->
<div class="container">
  <!--投稿などのメッセージ-->
  <% if flash[:notice] %>
    <p class=notice><%= flash[:notice] %></p>
  <% end %>
  <!--バリデーションのエラーメッセージ-->
  <% if @book.errors.any? %>
  <h3>2 errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   <% end %>
  <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= current_user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= current_user.introduction %></th>
      </tr>
      </tbody>
    </table>

    <%= link_to edit_user_path(current_user.id) do %>
      <div class="row">
　     <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
      </div>
    <% end %>

 <!--NewBook　新規投稿フォーム-->
    <h2>New book</h2>
    <%= form_with model:@book, local:true, class: :new_book do |f| %>
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'col-xs-12' %>
      </div>

      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_field :title, class: 'col-xs-12 book_body' %>
      </div>

      <div class="actions row">
        <%= f.submit('Create Book',class: 'btn btn-primary col-xs-12') %>
      </div>
     <% end %>
  </div>


<!--Usrs 投稿一覧表示-->
    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
          <tbody>
              <tr>
                  <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td><%= link_to 'Show', user_path(user.id) %></td>
              </tr>
          </tbody>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--User_infoフォーム-->
<div class="body">
      <div class="container">
      	<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
      	  <th>name</th>
      	  <th><%= @user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%= @user.introduction %></th>
        </tr>
        </tbody>
    </table>
    <%= link_to edit_user_path(@user.id) do %>
　   <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
    <% end %>

<!--NewBook　新規投稿フォーム-->
  <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
      <div class="field row">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: 'col-xs-12 book_title' %>
        </div>

        <div class="field row">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: 'col-xs-12 book_body' %><br>
        </div>

        <div class="actions row">
          <%= f.submit('Create Book',class: 'btn btn-primary col-xs-12') %>
        </div>
    <% end %>
      </div>

<!--Usrs 投稿一覧表示-->
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% @user.books.each do |book| %>
      <tbody>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
            <td><%=link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>
</div>
</div>