config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  'home#new'
  resources :users, only: [:show, :update, :edit, :index,]
  resources :books, only: [:create,:show, :update, :edit, :index,]
  resources :home, only: [:new] do
    get :about, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body,presence: true,length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


# form_withが空っぽであればcreateが起動する
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have createed book successfully.."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render action: :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully.."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render action: :edit
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    render action: :edit
    else
    redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def index
    @book  = Book.new
    @books = Book.all
  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @user = @books.user
  end


  private
  def profile_image_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  private
  def book_params
    params.require(:book).permit(:title,:body,:user_id)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
	<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>

    <!--バリデーションのエラ〜メッセージ-->
    <div id="error_explanation">
     <% if @book.errors.any? %>
      <h3>2 errors prohibited this obj from being saved:</h3>

        <ul>
          <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
      <% end %>
    </div>

	<%= form_with model:@book, local:true do |f| %>
  <div class="field row">
    <div class="field_with_errors"><label for="book_title">Title</label></div>
     <div><%= f.text_field :title, class: 'col-xs-12 book_title' %></div>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <div><%= f.text_area :body, class: 'col-xs-12 book_body' %></div>
  </div>

  <div class="actions row">
    <%= f.submit('Update Book',class: 'btn btn-primary col-xs-12') %>
  </div>
  <% end %>

  <div><%= link_to 'Show', book_path(@book.id) %></div>
  <div><%= link_to 'Back', books_path %></div><br>
  </div>
  <div class="col-md-3"></div>
</div>
</div>
</div>

app/views/books/index.html.erb
<!--User_infoフォーム-->
    <div class="body">
      <div class="container">
        <div id="error_explanation">
     <% if @book.errors.any? %>
      <h3>2 errors prohibited this obj from being saved:</h3>

        <ul>
          <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
      <% end %>
    </div>
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <th><%= attachment_image_tag current_user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %></th>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
      	  <th>name</th>
      	  <th><%= current_user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%= current_user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <%= link_to edit_user_path(current_user.id) do %>
      <div class="row">
　     <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
      </div>
    <% end %>

<!--NewBook　新規投稿フォーム-->
    <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'col-xs-12 book_title' %>
      </div>

      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: 'col-xs-12 book_body' %><br>
      </div>

      <div class="actions row">
        <%= f.submit('Create Book',class: 'btn btn-primary col-xs-12') %>
      </div>
     <% end %>
  </div>

 <!--Usrs 投稿一覧表示-->
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% @books.each do |book| %>
      <tbody>
          <tr>
            <td><%= link_to (attachment_image_tag book.user,:profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg"), user_path(book.user.id) %></td>
            <td><%=link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
      </tbody>
       <% end %>
    </table>
  </div>
  </div>
  </div>
  </div>

app/views/books/show.html.erb
<!--User_infoフォーム-->
<div class="container">
  <% if flash[:notice] %>
    <p class=notice><%= flash[:notice] %></p>
  <% end %>
  <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
      	  <th>name</th>
      	  <th><%= @books.user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%= @books.user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <%= link_to('edit_user_path') do %>
　   <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></div>
    <% end %>

<!--NewBook　新規投稿フォーム-->
    <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'col-xs-12 book_title' %>
      </div>

      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: 'col-xs-12 book_bod' %>
      </div>

      <div class="actions row">
        <%= f.submit('Create Book',class: 'btn btn-primary col-xs-12') %>
      </div>
     <% end %>
  </div>

 <!--Usrs 投稿一覧表示-->
  <div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
		  <tbody>
            <tr>
                <td>
                    <%= link_to(user_path @books.user.id) do %>
                      <%= attachment_image_tag @books.user,:profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br>
                      <%=@books.user.name %>
                    <% end %>
                  </td>
                  <td><%= @books.title %></td>
                  <td><%= @books.body %></td>
                <% if @books.user_id == current_user.id %>
                  <td><%= link_to 'Edit', edit_book_path(@books.id), class: 'btn-sm btn-success' %></td>
                  <td><%= link_to 'Destroy', book_path(@books.id), method: :delete, class: 'btn-sm btn-danger', "data-confirm" => "本当に消しますか？" %></td>
                <% end %>
            </tr>
        </tbody>
    </table>
  </div>
</div>
</div>