config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  'home#new'
  resources :users, only: [:show, :update, :edit, :index,]
  resources :books, only: [:create,:show, :update, :edit, :index,]
  resources :home, only: [:new] do
    get :about, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Bookers02</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="">
                <%= link_to 'Home', user_path(current_user.id), class: 'glyphicon glyphicon-home home' %>
              </li>
            <li class="">
                <%= link_to 'Users', users_path, class:'glyphicon glyphicon-user users' %>
              </li>
              <li class="">
                <%= link_to 'Books', books_path, class:'glyphicon glyphicon-book books' %>
              </li>
              <li class="">
                <%= link_to "logout", destroy_user_session_path, method: :delete, class:'glyphicon glyphicon-log-out logout' %>
              </li>
            <% else %>
              <li class="">
                <%= link_to "Home", root_path, class: 'glyphicon glyphicon-home home'  %>
              </li>
              <li class="">
                <%= link_to "About", about_home_index_path, class: 'glyphicon glyphicon-link about'  %>
              </li>
              <li class="">
                <%= link_to "Sign up", new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up'  %>
              </li>
              <li class="">
                <%= link_to "Login", new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'  %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

      <main>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: '#{key}') %>
        <% end %>

       <%= yield %>
      </main>

    <footer>
      <div class="container">
      	<div class="row">
        	<div class="col-xs-3 col-xs-offset-9">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>
  </body>
</html>